"""Initial migration

Revision ID: 98b4079aec8a
Revises: 
Create Date: 2024-12-09 18:16:36.405681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b4079aec8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE TABLE users (
        user_id         UUID NOT NULL DEFAULT uuid_generate_v4(), 
        first_name      VARCHAR NOT NULL, 
        last_name       VARCHAR NOT NULL, 
        email           VARCHAR NOT NULL, 
        password_hash   VARCHAR, 
        created_at      TIMESTAMP WITH TIME ZONE DEFAULT now(), 
        updated_at      TIMESTAMP WITH TIME ZONE DEFAULT now(), 
        
        PRIMARY KEY (user_id), 
        UNIQUE (email)
    );          
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE users;")
    # ### end Alembic commands ###
